export default function TermsPage() {
  return (
    <div style={{ backgroundColor: "#F9F7F4", minHeight: "100vh", color: "#2A2620" }}>
      <header style={{ padding: "28px 40px", borderBottom: "1px solid rgba(184,178,168,0.35)" }}>
        <a
          href="/"
          style={{
            fontFamily: "var(--font-playfair), Georgia, serif",
            fontSize: "28px",
            fontWeight: 700,
            color: "#3D5A3E",
            textDecoration: "none",
          }}
        >
          Sonder
        </a>
      </header>

      <main style={{ maxWidth: "680px", margin: "0 auto", padding: "60px 24px 80px" }}>
        <h1
          style={{
            fontFamily: "var(--font-playfair), Georgia, serif",
            fontSize: "clamp(24px, 3.5vw, 34px)",
            fontWeight: 600,
            color: "#2A2620",
            marginBottom: "8px",
          }}
        >
          Terms of Service
        </h1>
        <p style={{ fontSize: "13px", color: "#8A8278", marginBottom: "40px" }}>
          Last updated: April 2025
        </p>

        <div style={{ display: "flex", flexDirection: "column", gap: "28px" }}>
          <Section title="1. Nature of the Service">
            Sonder is a self-reflection tool designed for personal insight and general educational
            purposes. It is based on publicly validated psychological research frameworks including
            the IPIP-NEO, ECR-RS, O*NET Holland Codes, and VIA Character Strengths. Sonder is{" "}
            <strong>not</strong> a clinical assessment, a medical device, a diagnostic tool, or a
            substitute for professional mental health care, therapy, or counseling.
          </Section>

          <Section title="2. Not a Medical or Mental Health Service">
            Nothing on this website or in your report constitutes medical advice, psychiatric
            diagnosis, or therapeutic treatment. If you are experiencing emotional distress, a
            mental health crisis, or symptoms of a mental health condition, please seek help from a
            licensed professional. If you are in crisis, contact the 988 Suicide and Crisis
            Lifeline by calling or texting <strong>988</strong>.
          </Section>

          <Section title="3. Eligibility">
            By using Sonder, you confirm that you are at least 18 years of age. Sonder is not
            intended for use by minors.
          </Section>

          <Section title="4. Privacy and Data">
            Sonder does not collect, store, or transmit your assessment responses or personal
            results to any server. All data is processed locally in your browser and through a
            temporary, stateless API call to generate your report. We do not retain your answers,
            scores, or report after your session ends. See our{" "}
            <a href="/privacy" style={{ color: "#3D5A3E" }}>
              Privacy Policy
            </a>{" "}
            for full details.
          </Section>

          <Section title="5. Payment">
            The full report is available for a one-time payment of $5, processed securely through
            Stripe. All sales are final. Because your report is generated immediately and
            delivered digitally, refunds are not available once the report has been generated and
            displayed.
          </Section>

          <Section title="6. Accuracy and Limitations">
            Sonder provides general self-reflective insights based on your responses. Results are
            probabilistic, not deterministic — they reflect tendencies, not certainties. No
            psychological assessment tool is 100% accurate for any individual, and your results
            should be interpreted as a starting point for reflection, not a definitive description
            of who you are.
          </Section>

          <Section title="7. Intellectual Property">
            All content, design, copy, and report text generated by Sonder is the property of
            Sonder. Your generated report is for your personal use only and may not be resold,
            redistributed, or published commercially without permission.
          </Section>

          <Section title="8. Changes to These Terms">
            We may update these Terms of Service from time to time. Continued use of the service
            after changes are posted constitutes acceptance of the updated terms. The date at the
            top of this page reflects the most recent revision.
          </Section>
        </div>

        <p style={{ marginTop: "48px", fontSize: "13px", color: "#8A8278" }}>
          Questions? Contact us at{" "}
          <a href="mailto:hello@sonder-me.com" style={{ color: "#3D5A3E" }}>
            hello@sonder-me.com
          </a>
        </p>
      </main>

      <footer style={{ borderTop: "1px solid rgba(184,178,168,0.35)", padding: "28px 24px", textAlign: "center" }}>
        <div style={{ display: "flex", gap: "24px", justifyContent: "center" }}>
          <a href="/terms" style={{ fontSize: "12px", color: "#B8B2A8", textDecoration: "none" }}>
            Terms of Service
          </a>
          <a href="/privacy" style={{ fontSize: "12px", color: "#B8B2A8", textDecoration: "none" }}>
            Privacy Policy
          </a>
        </div>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2
        style={{
          fontFamily: "var(--font-playfair), Georgia, serif",
          fontSize: "17px",
          fontWeight: 600,
          color: "#2A2620",
          marginBottom: "10px",
        }}
      >
        {title}
      </h2>
      <p style={{ fontSize: "15px", color: "#5A5450", lineHeight: 1.75 }}>{children}</p>
    </div>
  );
}
